name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via SFTP
        run: |
          lftp -u "${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }}" sftp://${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PORT }} <<EOF
            set ssl:verify-certificate no
            set sftp:auto-confirm yes
            set net:max-retries 3
            set net:reconnect-interval-base 5
            set mirror:use-pget-n 8
            mirror -R \
              --verbose \
              --only-newer \
              --no-perms \
              --no-umask \
              --parallel=8 \
              --use-cache \
              --delete \
              dist/ \
              ${{ secrets.SFTP_PATH }}
            quit
          EOF
        shell: /usr/bin/bash -e {0}